export const MOD_REGISTER_STAGE = "MODIFY_REGISTER_STAGE";
export const INC_REGISTER_STAGE = "INCREMENT_REGISTER_STAGE";
export const DEC_REGISTER_STAGE = "DECREMENT_REGISTER_STAGE";

export const ADD_REGISTER_DATA = "ADD_REGISTER_DATA";

export const MOD_IDENTITY = "MODIFY_IDENTITY";
