export default [
  {
    id: "1",
    image: "",
    name: "Sarthak Karandikar",
    position: "CEO - CoFounder",
    linkedin: "",
  },
  {
    id: "2",
    image: "",
    name: "Aniket Devgune",
    position: "CFO - CoFounder",
    linkedin: "",
  },
  {
    id: "3",
    image: "",
    name: "Swanand Wagh",
    position: "CIO - CoFounder",
    linkedin: "https://www.linkedin.com/in/swanandwagh1208/",
  },
  {
    id: "4",
    image: "",
    name: "Sahil Gupte",
    position: "CTO - CoFounder",
    linkedin: "",
  },
  {
    id: "5",
    image: "",
    name: "Ojas Fernandez",
    position: "CoFounder",
    linkedin: "",
  },
  {
    id: "6",
    image: "",
    name: "Abhishek Choure",
    position: "Frontend Developer",
    linkedin: "",
  },
  {
    id: "7",
    image: "",
    name: "Shriya Gupta",
    position: "Frontend Developer",
    linkedin: "",
  },
  {
    id: "8",
    image: "",
    name: "Eswaran S.",
    position: "Frontend Developer",
    linkedin: "",
  },
  {
    id: "9",
    image: "",
    name: "Sohail",
    position: "UI-UX Designer",
    linkedin: "",
  },
  {
    id: "10",
    image: "",
    name: "ALIAS",
    position: "unknown",
    linkedin: "",
  },
];
